pipeline { 
   agent any 
   stages {
      stage ("build") {
        steps {
          echo "This is building environment"
          }
         }
      stage ("test") {
        steps {
          echo "This is testing environment"
          }
         }
      stage ("deploy") {
        steps {
           echo "This is deploying environment"
           }
          }
     }
